name: contracts

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Test
        working-directory: contracts
        run: forge test
