name: Docker

on:
  push:
    branches:
      - solochain
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and (optionally) push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./relayer
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/solochain' }}
          tags: |
            docker.io/moonsonglab/snowbridge-relayer:${{ github.ref == 'refs/heads/solochain' && 'latest' || format('pr-{0}', github.event.pull_request.number) }}
