name: Docker

on:
  push:
    branches:
      - main
    paths:
      - "relayer/**"
      - ".github/workflows/docker.yml"
  pull_request:
    paths:
      - "relayer/**"
      - ".github/workflows/docker.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and (optionally) push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./relayer
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            docker.io/moonsonglab/snowbridge-relayer:${{ github.ref == 'refs/heads/main' && 'latest' || format('pr-{0}', github.event.pull_request.number) }}
